### ISSUE TITLE
Sections - Project 4 - Remove reliance on auto margins and manual ordering of html

### ISSUE THREAD

**Issue by azariah001** [creativetimofficial/ct-paper-kit-2-pro#10]
I'm currently using this framework on a pretty large project and I'm finding some of the CSS choices.... confusing and somewhat sloppy. I'm noticing a reliance on things like auto margins where properly implemented Flex would be a lot better.

The most prominent example of this came up while implementing the Project 4 section styling on a page and I made the following revisions to make it much less fiddly to implement in a dynamic site.

````scss
/* SCSS */
.project-4 {
   > .container > .row {
        justify-content: center;
        &:nth-of-type(odd) > *:first-child {
            order: 1;
        }
    }
}
````
